USE [master]
GO

/****** Object:  Database [Contragents]    Script Date: 17.08.2017 14:27:26 ******/
CREATE DATABASE [Contragents]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Contragents.mdf', FILENAME = N'C:\USERS\XRONI\DOCUMENTS\GITHUB\TESTTHETASK\TESTTHETASK\TESTTHETASK\APP_DATA\Contragents.MDF' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Contragents_log.ldf', FILENAME = N'C:\USERS\XRONI\DOCUMENTS\GITHUB\TESTTHETASK\TESTTHETASK\TESTTHETASK\APP_DATA\Contragents_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Contragents] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Contragents].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Contragents] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Contragents] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Contragents] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Contragents] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Contragents] SET ARITHABORT OFF 
GO

ALTER DATABASE [Contragents] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [Contragents] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Contragents] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Contragents] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Contragents] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Contragents] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Contragents] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Contragents] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Contragents] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Contragents] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Contragents] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Contragents] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Contragents] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Contragents] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Contragents] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Contragents] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [Contragents] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Contragents] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Contragents] SET  MULTI_USER 
GO

ALTER DATABASE [Contragents] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Contragents] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Contragents] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Contragents] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Contragents] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Contragents] SET QUERY_STORE = OFF
GO

USE [Contragents]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [Contragents] SET  READ_WRITE 
GO

